### ISSUE TITLE
顶部导航栏

### ISSUE THREAD

**Issue by dyike** [snokier/flat-weibo#1]
顶部导航栏得固定刷首页，我测试了几次，侧栏有不固定的时候。

**Comment by CyberNika** [comment]
`顶部导航栏得固定刷首页`是什么意思？侧栏的 `fixed` 应该是没有改动的。可否截个图？

**Comment by dyike** [comment]
侧栏是fixed，我重新安装了就可以了。但我觉得顶部的导航栏得fixed，刷新首页是可以点侧栏的。但刷了好多微博，我想发条微博时，这时候还得点击那个向上箭头。。。你看原微博顶部是不是fixed？我的描述不太准确，嘿嘿，你应该能明白那个意思的。

**Comment by CyberNika** [comment]
先谢谢你的反馈 :)
恩，明白你的意思。是因为鉴于有返回顶部的箭头，并且发微博可以直接按 `n`，所以我把顶部导航的 `fixed` 去掉了。让我考虑考虑要不要改回去。
